name: Test Suite
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-inclusive-naming-check:
    name: Inclusive naming
    uses: canonical-web-and-design/Inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"

  lint-unit:
    name: Lint Unit
    uses: charmed-kubernetes/workflows/.github/workflows/lint-unit.yaml@main
    needs:
      - call-inclusive-naming-check
    with:
      python: "['3.8', '3.9', '3.10']"

  integration-test:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
            provider: microk8s
      - name: Run test
        run: tox -e integration
